#pragma once
#include <iostream>
#include "Processor.hh"
#include "Register16bit.hh"
#include "Register8bit.hh"
#include "TestUtils.hh"

namespace TestCPU {
void runAllTests();
bool testLoadReg();
bool testLoadIntoMem();
bool testLoadIntoMemIm();
bool testLoadFromMem();
bool testLoadFromMemIm();
bool testRegisterIncrement();
bool testRegisterDecrement();
bool testRegiserCopy();
bool testRegisterSubtraction();
bool testRegisterAddCarry();
bool testRegisterSubCarry();
bool testRegisterAND();
bool testRegisterXOR();
bool testRegisterOR();
bool testRegisterCMP();
bool testStackPush();
bool testStackPop();
bool testStackPopAF();
bool testJump();
bool testJumpIm();
bool testRegisterRLC();
bool testRegisterRRC();
bool testRegisterRL();
bool testRegisterRR();
bool testRegisterSLA();
bool testRegisterSRA();
bool testSwapNibble();
bool testRegisterSRL();
bool testBitTest();
bool testBitReset();
bool testBitSet();
}  // namespace TestCPU